### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by gewitterblitz** [deeplycloudy/xlma-python#7]
I setup a conda environment for glue followed by glue installation (it works just fine). Then cloned the xlma-python repo on desktop. Within the glue environment, executed the python setup.py install. 

But when I try launching glue from xlma-python/examples/glueviz/  I get the following error.

ModuleNotFoundError: ("Error loading config file /Users/ms/Desktop/xlma-python/examples/glueviz/config.py:\nNo module named 'pyxlma.lmalib'", <traceback object at 0x11a4d4b08>)

Where am I going wrong with this?

**Comment by deeplycloudy** [comment]
You need to run python setup.py install from the top level project directory to install the pyxlma package. Or pip install -e . to allow you to edit pyxlma and not have to reinstall every time.

**Comment by gewitterblitz** [comment]
For some weird reason, python setup.py install (from the top level project directory) did not work for me. 

Deleted the 'anaconda3/envs/glue/lib/python3.7/site-packages/pyxlma-0.0.0-py3.7.egg' file and then proceeded with pip install -e . 

I can visualize my LMA.gz file in the glue qt app . now. 

Thanks!

**Comment by deeplycloudy** [comment]
Glad it's working, now!
